### ISSUE TITLE
Feature question

### ISSUE THREAD

**Issue by npuldon** [raiguard/Factorio-BlueprintTools#1]
Does this mod allow you to quickly add landfill to a blueprint (or better yet to all blueprints in a book)?  If not, that would be a great feature so the user doesn't have to go through [this routine](https://www.reddit.com/r/factorio/comments/hrmbab/how_to_make_perfect_landfill/?utm_medium=android_app&utm_source=share). I saw in your mod description that you said 'tiles' but I wasn't sure if that included landfill or not.

Cheers

Update: Looks like this feature works with single blueprints but not a collection of blueprints in a book yet.

**Comment by raiguard** [comment]
Yes, it does allow you to landfill individual blueprints. I'm not sure I want to add landfilling to entire blueprint books at a time, that is extremely prone to error.

**Comment by npuldon** [comment]
Sounds good.  Best use case is a rail network book I guess for the BP book feature request.

Cheers
