### ISSUE TITLE
Crash when setting tiles on blueprint with only transport drone road tiles

### ISSUE THREAD

**Issue by jingleheimer-schmidt** [raiguard/Factorio-BlueprintTools#2]
#### Describe the Bug

blueprint tools crashes when setting tiles on a blueprint with only transport drone road tiles in it:
```
The mod Blueprint Tools (1.0.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event BlueprintTools::on_gui_click (ID 1)
__BlueprintTools__/scripts/processors/set-tiles.lua:67: bad argument #1 of 2 to 'pairs' (table expected, got nil)
stack traceback:
	[C]: in function 'pairs'
	__BlueprintTools__/scripts/processors/set-tiles.lua:67: in function 'set_tiles'
	__BlueprintTools__/scripts/gui/set-tiles.lua:112: in function 'handle_action'
	__BlueprintTools__/control.lua:103: in function <__BlueprintTools__/control.lua:86>
```

Quick edit to add that this crash happens regardless of what kind of tiles are used. I believe it happens because the script is expecting an entity in the blueprint, but there are no entities, only tiles.

#### To Reproduce

1. Install the transport drones mod
2. make a blueprint with only road tiles
3. set tiles as landfill to be placed under the road tiles

Be certain to reproduce the issue on the same save file that you upload.

#### Save file & Username

[reddit community map may 2021.zip](https://github.com/raiguard/Factorio-BlueprintTools/files/6425721/reddit.community.map.may.2021.zip)
username is asher_sky

#### Log file

[factorio-current.log](https://github.com/raiguard/Factorio-BlueprintTools/files/6425725/factorio-current.log)

**Comment by raiguard** [comment]
Thanks, fixed for the next version. This also happened with quick grid, so I fixed it there as well.
