### ISSUE TITLE
The blueprint name cover some function description

### ISSUE THREAD

**Issue by Xzzuh** [raiguard/Factorio-BlueprintTools#3]
This is a Simple question. Sorry that I won't follow the template. 
（English is not my native language, I am using some translation tools, sorry. )

#### Describe the Bug

The blueprint name will cover the function description. Just like the picture. 
![E 1YOPQE1LZQEQ0KAZ5094Q](https://user-images.githubusercontent.com/88430768/128161556-a6ad1deb-7166-4363-b572-f7861947a366.png)

#### To Reproduce

1. Get a non-empty blueprint with a name.
2. Move to the mod function button.
3. Try to look over the function description.

**Comment by raiguard** [comment]
Unfortunately, I can't do anything about this. This would need to be reported to the Factorio developers.

Thanks for the report though!

**Comment by Xzzuh** [comment]
I read your reply 12 hours ago. I was sad at first. 
But I suddenly reminded a little trick. The "\n". Yeah, "\n"
And I try it, it works good. It works like this. 
![1](https://user-images.githubusercontent.com/88430768/128333582-c135d4a5-336a-41ba-8c9c-6b942baef591.png)
Maybe it becomes uglier. But we can see the function description now! OHHHHHHHHHH!!

#### To Reproduce

Steps to reproduce the behavior:

1. Open  .\locale\en\BlueprintTools.cfg
2. Add "\n\n" to the front of *** (__CONTROL__***__)
3. Save all files. Do some testing and upload updates. 
### Just like the picture!
![2](https://user-images.githubusercontent.com/88430768/128333604-58677df8-8954-4e79-8d38-91b1eb974ce7.png)

Good luck!

**Comment by raiguard** [comment]
After the first few times using the buttons you've probably memorized what they do anyway.

Also, you can already avoid this by increasing the `tooltip offset` setting in Factorio's interface settings:

![image](https://user-images.githubusercontent.com/3515394/128808038-fd648c2e-087e-45d9-b8b6-3b9bef41ad98.png)

**Comment by Xzzuh** [comment]
Okey, thank you. The tooltip offset a real solution.
