### ISSUE TITLE
Blueprint Tools does nothing

### ISSUE THREAD

**Issue by jaybocc2** [raiguard/Factorio-BlueprintTools#6]
_PLEASE FOLLOW THIS TEMPLATE EXACTLY. ALL OF THIS INFORMATION IS REQUIRED IN ORDER TO BE ABLE TO REPRODUCE AND FIX THE ISSUE._

#### Describe the Bug

Blueprint tools does nothing, No functionality appears to work at all.  Factorio 1.1.38

#### To Reproduce
[factorio-current.log](https://github.com/raiguard/Factorio-BlueprintTools/files/7071794/factorio-current.log)

```
Load Game/Save, try to load/use blueprint tools.
Nothing happens (no shortcuts work)
Rebind shortcuts (shift+alt+b)
Nothing still.
Restart game, reload, save, reload, restart etc. no blueprint tools.
```
Be certain to reproduce the issue on the same save file that you upload.

#### Save file & Username

Upload the save file where the bug occured. If the file is too large for GitHub, use an alternative file service or split the file into multiple parts using 7-zip.
[Spaghet-1.6.4g.zip](https://github.com/raiguard/Factorio-BlueprintTools/files/7071796/Spaghet-1.6.4g.zip)

Provide your in-game username. This is required in order to be able to reproduce the conditions exactly. `JayBoCC2`

#### Log file

Attach `factorio-current.log`, found in Factorio's [user data directory](https://wiki.factorio.com/Application_directory#User_data_directory).

**Comment by raiguard** [comment]
Go to the mods screen and make sure you have the Factorio library mod enabled. It's a dependency that this mod needs in order to function.

**Comment by jaybocc2** [comment]
@raiguard It is installed and enabled, many of the other utility mods i enjoy require/depend on it as well.

**Comment by raiguard** [comment]
Make sure you're holding a blueprint that has been configured. You should see several buttons appear in the top-left.

**Comment by raiguard** [comment]
Were you able to get it working?

**Comment by jaybocc2** [comment]
Mod only works on new bps unfortunately I needed the functionality on existing blueprints so maybe my intended use is not supported.  If so you can close.

**Comment by raiguard** [comment]
OH. It doesn't work on blueprints in the blueprint library. That's a known issue and I literally cannot do anything about it. Mods cannot touch the blueprint library at all.
