### ISSUE TITLE
Mod Setting to disable each of mod's features

### ISSUE THREAD

**Issue by nicolas-lang** [raiguard/Factorio-BlueprintTools#7]
#### Is your feature request related to a problem? Please describe.

I like to play heavily modded games, and all the hotkeys + commands pollute the game's UI very fast.

#### Describe the solution you'd like

I would like to have a setting to enable/disable each of mod's features (add grid, swap wire, add tiles, open settings) I probably would never use the wire swap but i love the add-tile feature.
disabling a feature should remove the hotkey* and hide the UI button. 
*(Assuming the setting being a map/mod setting)
#### Additional context
While I like the possibility to set something "per player" it is also a responsibility of the map/server admin to provide a clean UI and a playable game. Since I don't think there is something like "map-provided-defaults" for the per player settings, I would prefer this as a map setting, but I can understand the reasoning of it being per player.

**Comment by raiguard** [comment]
I added settings to show/hide the buttons. To disable the hotkeys, unbind them from the controls menu.

**Comment by nicolas-lang** [comment]
It works as expected and I am really happy with it, thanks a lot for implementing.
