### ISSUE TITLE
Save previously selected tile and border in "tile-gui"

### ISSUE THREAD

**Issue by nicolas-lang** [raiguard/Factorio-BlueprintTools#8]
#### Is your feature request related to a problem? Please describe.
My main use-case for the mod would be to add landfill under some rails on nauvis, and to add space-platforms under my factory in space( playing space-exploration)
With this mainly being a QOL mod I feel like my life could be improved even more with having to do less clicks.

#### Describe the solution you'd like
- I would like the add-tiles feature to save my previously selected tile-type and border-size, while still allowing me to change it using the current gui (just pre-select the previously use values)
- I would like to have a mod-setting (csv-separated string with tile prototype names) to blacklist specific tile types since they don't make sense as a Ghost (K2-Biter-Creep for example)

**Comment by raiguard** [comment]
Turns out that you actually _can't_ filter files in the choose tiles GUI by name. That seems like an oversight and I'll be making an API request for it. So for now, we'll have to deal with biter creep being in the menu.
