### ISSUE TITLE
Game crash when grabing blueprint

### ISSUE THREAD

**Issue by sakari119** [raiguard/Factorio-BlueprintTools#9]
The mod Blueprint Tools (1.1.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event BlueprintTools::on_player_cursor_stack_changed (ID 30)
Index out of inventory bounds.
stack traceback:
	[C]: in function '__index'
	__BlueprintTools__/scripts/util.lua:13: in function 'get_blueprint'
	__BlueprintTools__/control.lua:125: in function <__BlueprintTools__/control.lua:119>

**Comment by raiguard** [comment]
Please upload a save file and give exact reproduction steps.
